### ISSUE TITLE
youtube-dl is currently not working with YouTube URLs

### ISSUE THREAD

**Issue by hifihedgehog** [MrS0m30n3/youtube-dl-gui#406]
This issue appears to impact all current public releases of youtube-dl and all programs in existence that rely on its current dependencies. Awaiting a new release when the fix comes for youtube-dl and that is integrated here.

**Comment by QPUNeptune** [comment]
did you try pressing update to update the youtube-dl?

**Comment by Dunothar** [comment]
should be fixed on side of Youtube. Was able to download Videos and watch them directly in another player like MPC-BE again.

**Comment by SYNCHRONIC** [comment]
Anyone manage to sort this out? Still can't download any YouTube videos, tried updating from within the GUI, manually replacing the .exe, re-downloading the latest portable and installer versions.

Still just get "0%" - Error everytime.
